In [ ]:
import pandas as pd
import numpy as np

# Cargar el conjunto de datos
file_path = 'sample_data/vgsales.csv'
data = pd.read_csv(file_path)
print(data.head())

   Rank                      Name Platform    Year         Genre Publisher  \
0     1                Wii Sports      Wii  2006.0        Sports  Nintendo
1     2         Super Mario Bros.      NES  1985.0      Platform  Nintendo
2     3            Mario Kart Wii      Wii  2008.0        Racing  Nintendo
3     4         Wii Sports Resort      Wii  2009.0        Sports  Nintendo
4     5  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing  Nintendo

   NA_Sales  EU_Sales  JP_Sales  Other_Sales  Global_Sales
0       NaN     29.02      3.77         8.46         82.74
1     29.08      3.58      6.81         0.77         40.24
2     15.85     12.88      3.79         3.31         35.82
3     15.75     11.01      3.28         2.96         33.00
4     11.27      8.89     10.22         1.00         31.37

In [ ]:

# Seleccionar las columnas de interés
selected_columns = data[['Name', 'Platform', 'Year', 'Genre', 'Global_Sales']]
print(selected_columns.head())

                       Name Platform    Year         Genre  Global_Sales
0                Wii Sports      Wii  2006.0        Sports         82.74
1         Super Mario Bros.      NES  1985.0      Platform         40.24
2            Mario Kart Wii      Wii  2008.0        Racing         35.82
3         Wii Sports Resort      Wii  2009.0        Sports         33.00
4  Pokemon Red/Pokemon Blue       GB  1996.0  Role-Playing         31.37

In [ ]:

# Verificar valores faltantes
missing_values = selected_columns.isnull().sum()
print(missing_values)

Name              0
Platform          0
Year            271
Genre             0
Global_Sales      0
dtype: int64

In [ ]:
# Eliminar filas con valores faltantes en la columna 'Year'
cleaned_data = selected_columns.dropna(subset=['Year'])
print(cleaned_data)

                                                   Name Platform    Year  \
0                                            Wii Sports      Wii  2006.0
1                                     Super Mario Bros.      NES  1985.0
2                                        Mario Kart Wii      Wii  2008.0
3                                     Wii Sports Resort      Wii  2009.0
4                              Pokemon Red/Pokemon Blue       GB  1996.0
...                                                 ...      ...     ...
16593                Woody Woodpecker in Crazy Castle 5      GBA  2002.0
16594                     Men in Black II: Alien Escape       GC  2003.0
16595  SCORE International Baja 1000: The Official Game      PS2  2008.0
16596                                        Know How 2       DS  2010.0
16597                                  Spirits & Spells      GBA  2003.0

              Genre  Global_Sales
0            Sports         82.74
1          Platform         40.24
2            Racing         35.82
3            Sports         33.00
4      Role-Playing         31.37
...             ...           ...
16593      Platform          0.01
16594       Shooter          0.01
16595        Racing          0.01
16596        Puzzle          0.01
16597      Platform          0.01

[16327 rows x 5 columns]

In [ ]:
# Convertir la columna 'Year' a enteros
cleaned_data['Year'] = cleaned_data['Year'].astype(int)
print(cleaned_data)

                                                   Name Platform  Year  \
0                                            Wii Sports      Wii  2006
1                                     Super Mario Bros.      NES  1985
2                                        Mario Kart Wii      Wii  2008
3                                     Wii Sports Resort      Wii  2009
4                              Pokemon Red/Pokemon Blue       GB  1996
...                                                 ...      ...   ...
16593                Woody Woodpecker in Crazy Castle 5      GBA  2002
16594                     Men in Black II: Alien Escape       GC  2003
16595  SCORE International Baja 1000: The Official Game      PS2  2008
16596                                        Know How 2       DS  2010
16597                                  Spirits & Spells      GBA  2003

              Genre  Global_Sales
0            Sports         82.74
1          Platform         40.24
2            Racing         35.82
3            Sports         33.00
4      Role-Playing         31.37
...             ...           ...
16593      Platform          0.01
16594       Shooter          0.01
16595        Racing          0.01
16596        Puzzle          0.01
16597      Platform          0.01

[16327 rows x 5 columns]

<ipython-input-29-7f497cfffea8>:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  cleaned_data['Year'] = cleaned_data['Year'].astype(int)

In [ ]:
# Filtrar los datos para extraer juegos publicados en la plataforma 'Wii'
wii_games = cleaned_data[cleaned_data['Platform'] == 'Wii']
print(wii_games.head())

                        Name Platform  Year     Genre  Global_Sales
0                 Wii Sports      Wii  2006    Sports         82.74
2             Mario Kart Wii      Wii  2008    Racing         35.82
3          Wii Sports Resort      Wii  2009    Sports         33.00
7                   Wii Play      Wii  2006      Misc         29.02
8  New Super Mario Bros. Wii      Wii  2009  Platform         28.62

In [41]:
# Filtrar los datos para extraer juegos publicados en el año '2002'
Year = data[data['Year'] > 2002]
print(Year.head())

   Rank                   Name Platform    Year     Genre Publisher  NA_Sales  \
0     1             Wii Sports      Wii  2006.0    Sports  Nintendo       NaN
2     3         Mario Kart Wii      Wii  2008.0    Racing  Nintendo     15.85
3     4      Wii Sports Resort      Wii  2009.0    Sports  Nintendo     15.75
6     7  New Super Mario Bros.       DS  2006.0  Platform  Nintendo     11.38
7     8               Wii Play      Wii  2006.0      Misc  Nintendo       NaN

   EU_Sales  JP_Sales  Other_Sales  Global_Sales
0     29.02      3.77         8.46         82.74
2     12.88      3.79         3.31         35.82
3     11.01      3.28         2.96         33.00
6      9.23      6.50         2.90         30.01
7      9.20      2.93         2.85         29.02

In [44]:

# Seleccionar las columnas de interés
selected_columns_country = data[[ 'NA_Sales' ,'EU_Sales', 'JP_Sales', 'Other_Sales']]
print(selected_columns_country.head())

   NA_Sales  EU_Sales  JP_Sales  Other_Sales
0       NaN     29.02      3.77         8.46
1     29.08      3.58      6.81         0.77
2     15.85     12.88      3.79         3.31
3     15.75     11.01      3.28         2.96
4     11.27      8.89     10.22         1.00

In [ ]:
# Verificar valores faltantes
missing_values = selected_columns_country.isnull().sum()
print(missing_values)

NA_Sales       4
EU_Sales       0
JP_Sales       0
Other_Sales    0
dtype: int64

In [39]:
#eliminar filas con cvalores nulos
cleaned_data_country = selected_columns_country.dropna()

In [40]:
#verificar valore nulos despues de eliminar
print("valores nulos despues de eliminar:")
print(cleaned_data_country.isnull().sum())

valores nulos despues de eliminar:
NA_Sales       0
EU_Sales       0
JP_Sales       0
Other_Sales    0
dtype: int64

In [46]:
ventas_columns = ['NA_Sales', 'EU_Sales', 'JP_Sales', 'Other_Sales', 'Global_Sales']
promedios_ventas = Year[ventas_columns].mean()
print("promedios de evntas por region despues del 2002:")
print(promedios_ventas)

promedios de evntas por region despues del 2002:
NA_Sales        0.234929
EU_Sales        0.144778
JP_Sales        0.053974
Other_Sales     0.053006
Global_Sales    0.491320
dtype: float64